language: objective-c
osx_image: xcode9.4
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=SourceEditor.xcworkspace
  - IOS_FRAMEWORK_SCHEME="SourceEditor"
  - MACOS_FRAMEWORK_SCHEME="SourceEditor"
  matrix:

    - DESTINATION="OS=11.4,name=iPad Pro (9.7-inch)"    SCHEME="$IOS_FRAMEWORK_SCHEME"
    # - DESTINATION="arch=x86_64"                         SCHEME="$MACOS_FRAMEWORK_SCHEME" 

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    bash <(curl -s https://codecov.io/bash);
    fi